from __future__ import annotations

from typing import Protocol, Any


class SignatureBackend(Protocol):
    """CPU/GPU backend interface for the benchmark harness."""

    def name(self) -> str: ...
    def keygen(self) -> tuple[Any, Any]: ...
    def sign(self, sk: Any, message: bytes) -> Any: ...
    def verify(self, pk: Any, message: bytes, signature: Any) -> bool: ...
